export enum PermissionsEnum {
	GET_OPERATIONS = "GET_OPERATIONS",
	CREATE_OPERATIONS = "CREATE_OPERATIONS",
	REJECT_OPERATION = "REJECT_OPERATION",
	CREATE_ORDERS = "CREATE_ORDERS",
	APPROVE_OPERATION = "APPROVE_OPERATION",
	GET_ORDERS = "GET_ORDERS",
}
