name: Lint Biome

on:
    workflow_call: 

jobs:
    lint-ms-auth-dev:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ms-auth

        permissions: 
            contents: read
        
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  persist-credentials: false

            - name: Setup Biome
              uses: biomejs/setup-biome@v2
              with:
                version: latest
            
            - name: Run Biome
              run: biome ci .